// <auto-generated />
namespace WebApplication1Personen_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _firmer_mit_person_verknuepfen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_firmer_mit_person_verknuepfen));
        
        string IMigrationMetadata.Id
        {
            get { return "202010230738511__firmer_mit_person_verknuepfen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
