// <auto-generated />
namespace WebApplication1Personen_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mn_firma_personen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mn_firma_personen));
        
        string IMigrationMetadata.Id
        {
            get { return "202011060958423_mn_firma_personen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
