// <auto-generated />
namespace WebApplication1Personen_EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1020_firmenHinzugefuegt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1020_firmenHinzugefuegt));
        
        string IMigrationMetadata.Id
        {
            get { return "202010200747476_1020_firmenHinzugefuegt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
